# Generated by Django 5.1.1 on 2024-10-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0005_alter_tasks_author_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labels.labels')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(through='tasks.LabelsTasks', to='labels.labels'),
        ),
    ]
