# Generated by Django 5.1.1 on 2024-10-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0007_alter_labelstasks_label_alter_labelstasks_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.LabelsTasks', to='labels.labels', verbose_name='Labels'),
        ),
    ]
