# Generated by Django 5.1.1 on 2024-10-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0009_alter_tasks_labels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labelstasks',
            unique_together={('task', 'label')},
        ),
    ]
