# Generated by Django 5.1.1 on 2024-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_statuses_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
