# Generated by Django 5.1.1 on 2024-10-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_statuses_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuses',
            options={'verbose_name': 'Task status'},
        ),
    ]
